-- AlterTable
ALTER TABLE `lugar` ADD COLUMN `agua` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `riqueza` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `saude` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `seguranca` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `personagem` ADD COLUMN `personalidade` VARCHAR(2000) NULL;
